---
- name: "Add an upstart conf: {{ script_name }}"
  template:
    src: upstart_template.conf.j2
    dest: "/etc/init/{{script_name}}.conf"
    owner: root
    group: root
    mode: 0644
  tags:
    - upstart

- name: "Make sure script is running: {{ script_name }}"
  service:
    name: "{{ script_name }}"
    state: started
    enabled: yes
  tags:
    - upstart